[Endpoint] Retry execution if critical error occurs
Example of critical error : NoClassDefFoundError

In those case, we need to destroy the instance and re-initialiaze it